{{ if .Values.config_override }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: rook-config-override
  namespace: rook-ceph
data:
  config: |
    [global]
    {{ range $key, $value := .Values.config_override}}
    {{ $key }} = {{ $value }}
    {{- end }}
{{- end }}
# public network =  {{ .Values.cluster.network.public_net }}
# cluster network = {{ .Values.cluster.network.cluster_net }}
# public addr = ""
# cluster addr = ""
